[project]
name = "transformer-maskgit"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "accelerate",
    "beartype",
    "einops>=0.6",
    "ema-pytorch>=0.2.2",
    "opencv-python",
    "pillow",
    "numpy",
    "sentencepiece",
    "torch>=1.6",
    "torchtyping",
    "torchvision",
    "transformers",
    "tqdm",
    "vector-quantize-pytorch==1.1.2",
    "nibabel",
    "openpyxl",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
